### ISSUE TITLE
OFSHACKATHON: Undefined variable: show_assignment in /opt/omegaup/frontend/www/arena/course.php on line 24

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#1066]
```\nNotice: Undefined variable: show_assignment in /opt/omegaup/frontend/www/arena/course.php on line 24
2017-02-23T22:41:21+00:00 [ERROR]: 58af651188326401920940 /api/course/createAssignment/ exception 'ADODB_Exception' with message 'mysqli error: [1062: Duplicate entry '2-testhw1' for key 'assignment_alias'] in EXECUTE("INSERT INTO Assignments (`assignment_id`, `course_id`, `problemset_id`, `acl_id`, `name`, `description`, `alias`, `publish_time_delay`, `assignment_type`, `start_time`, `finish_time`) VALUES (NULL, '2', 5, '3', 'testhw2', 'testhw', 'testhw1', NULL, 'homework', '2017-02-23 22:40:00', '2017-02-24 03:40:00');")
' in /opt/omegaup/frontend/server/libs/third_party/adodb/adodb-exceptions.inc.php:78
Stack trace:
#0 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1224): adodb_throw()
#1 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1164): ADOConnection->_Execute()
#2 /opt/omegaup/frontend/server/libs/dao/base/Assignments.dao.base.php(261): ADOConnection->Execute()
#3 /opt/omegaup/frontend/server/libs/dao/base/Assignments.dao.base.php(42): AssignmentsDAOBase::create()
#4 /opt/omegaup/frontend/server/controllers/CourseController.php(248): AssignmentsDAOBase::save()
#5 /opt/omegaup/frontend/server/libs/Request.php(72): CourseController::apiCreateAssignment()
#6 /opt/omegaup/frontend/www/api/ApiCaller.php(31): Request->execute()
#7 /opt/omegaup/frontend/www/api/ApiCaller.php(52): ApiCaller::call()
#8 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()
#9 {main}

Next exception 'InvalidDatabaseOperationException' with message 'generalError' in /opt/omegaup/frontend/server/controllers/CourseController.php:250```

**Comment by elendil326** [comment]
@alanboy @lhchavez repro steps?

**Comment by pabloaguilar** [comment]
Creo que esto ya se cerro.
El mensaje de error en el titulo se arreglo en el commit 3c0b0444d3d60f3d86cbacba5dd4c79f1eeb7673
Y el mensaje de error en la descripcion se arreglo cuando nos aseguramos que el Primary key de un assignment fuera la tupla (course_id, assignment_alias)
