### ISSUE TITLE
Error al editar fecha fin de un curso

### ISSUE THREAD

**Issue by pacharrin** [omegaup/omegaup#1976]
Poder editar la fecha de un concurso que esta a punto de terminar
## Comportamiento Actual

- Intenté editar la fecha fin del [curso introductorio de la OMI](https://omegaup.com/course/Curso-OMI/edit/)
- Puse la nueva fecha de fin 05/31/2019
- Le di click en guardar
- Me mando error `Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.`
- En la consola apareció el error `{"status":"error","error":"Oops. Ocurri\u00f3 un error interno. Por favor int\u00e9ntalo nuevamente.","errorname":"generalError","errorcode":400,"header":"HTTP\/1.1 400 BAD REQUEST"}` 

## Comportamiento Esperado

* Que al dar click se guarde

**Comment by pacharrin** [comment]
también falla al intentar crear un curso nuevo

![image](https://user-images.githubusercontent.com/848246/39676993-97e41ce8-5139-11e8-8fa5-7f8c0af29c07.png)

**Comment by pacharrin** [comment]
El error es que la escuela es obligatoria y no falla gracefully

**Comment by lhchavez** [comment]
```
2018-05-06T18:09:40+00:00 [ERROR]: 5aef44e45658a555773742 /api/course/update/ ADODB_Exception: mysqli error: [1452: Cannot add or update a child row: a foreign key constraint fails (`omegaup`.`Courses`, CONSTRAINT `fk_school_id` FOREIGN KEY (`school_id`) REFERENCES `Schools` (`school_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)] in EXECUTE("UPDATE `Courses` SET `name` = 'Curso introductorio a la OMI', `description` = 'Este curso está diseñado para ser el punto de entrada a la Olimpiada de Informática para programadores principiantes.\nSe incluyen también explicaciones sobre cómo resolver los problemas.', `alias` = 'Curso-OMI', `group_id` = '447', `acl_id` = '77078', `start_time` = '2017-11-12 06:00:00', `finish_time` = '2019-04-01 05:59:59', `public` = '1', `school_id` = '', `needs_basic_information` = 0, `requests_user_information` = 'no' WHERE `course_id` = '206';") in /opt/omegaup/frontend/server/libs/third_party/adodb/adodb-exceptions.inc.php:80
Stack trace:
#0 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1265): adodb_throw('mysqli', 'EXECUTE', 1452, 'Cannot add or u...', 'UPDATE `Courses...', false, Object(ADODB_mysqli))
#1 /opt/omegaup/frontend/server/libs/third_party/adodb/adodb.inc.php(1205): ADOConnection->_Execute('UPDATE `Courses...')
#2 /opt/omegaup/frontend/server/libs/dao/base/Courses.dao.base.php(228): ADOConnection->Execute('UPDATE `Courses...', Array)
#3 /opt/omegaup/frontend/server/libs/dao/base/Courses.dao.base.php(40): CoursesDAOBase::update(Object(Courses))
#4 /opt/omegaup/frontend/server/controllers/CourseController.php(1534): CoursesDAOBase::save(Object(Courses))
#5 /opt/omegaup/frontend/server/libs/Request.php(72): CourseController::apiUpdate(Object(Request))
#6 /opt/omegaup/frontend/www/api/ApiCaller.php(31): Request->execute()
#7 /opt/omegaup/frontend/www/api/ApiCaller.php(83): ApiCaller::call(Object(Request))
#8 /opt/omegaup/frontend/www/api/ApiEntryPoint.php(5): ApiCaller::httpEntryPoint()
#9 {main}
```

**Comment by lhchavez** [comment]
ah me ganaste. sí, ese es el root cause.
