### ISSUE TITLE
Los envíos de String Binario Secreto se quedan atorados en new.

### ISSUE THREAD

**Issue by frcepeda** [omegaup/omegaup#2316]
Al hacer envíos de este problema el status se queda en new. No hay repro con otros problemas interactivos o con otros no interactivos.

Log de evaluación:
```t=2019-01-12T16:47:29+0000 lvl=dbug msg="served run" id=1742189 run="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792790 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" client=omegaup-v2-runner3.eastus2.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=dbug msg="Processing file" id=1742189 attempt_id=2637165062400792790 filename=files.zip runner=omegaup-v2-runner3.eastus2.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=eror msg="Unable to upload results" id=1742189 err="client disconnected" runner=omegaup-v2-runner3.eastus2.cloudapp.azure.com stack="[main.processRun(omegaup-grader/handler.go:177) main.registerHandlers.func4(omegaup-grader/handler.go:392)]"
t=2019-01-12T16:47:29+0000 lvl=eror msg="run errored out. retrying" id=1742189 context="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792790 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" stack=[main.registerHandlers.func4(omegaup-grader/handler.go:399)]
t=2019-01-12T16:47:29+0000 lvl=dbug msg="served run" id=1742189 run="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792791 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" client=omegaup-v2-runner1.eastus.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=dbug msg="Processing file" id=1742189 attempt_id=2637165062400792791 filename=files.zip runner=omegaup-v2-runner1.eastus.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=eror msg="Unable to upload results" id=1742189 err="client disconnected" runner=omegaup-v2-runner1.eastus.cloudapp.azure.com stack="[main.processRun(omegaup-grader/handler.go:177) main.registerHandlers.func4(omegaup-grader/handler.go:392)]"
t=2019-01-12T16:47:29+0000 lvl=eror msg="run errored out. retrying" id=1742189 context="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792791 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" stack=[main.registerHandlers.func4(omegaup-grader/handler.go:399)]
t=2019-01-12T16:47:29+0000 lvl=dbug msg="served run" id=1742189 run="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792792 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" client=omegaup-v2-runner2.eastus2.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=dbug msg="Processing file" id=1742189 attempt_id=2637165062400792792 filename=files.zip runner=omegaup-v2-runner2.eastus2.cloudapp.azure.com
t=2019-01-12T16:47:29+0000 lvl=eror msg="Unable to upload results" id=1742189 err="client disconnected" runner=omegaup-v2-runner2.eastus2.cloudapp.azure.com stack="[main.processRun(omegaup-grader/handler.go:177) main.registerHandlers.func4(omegaup-grader/handler.go:392)]"
t=2019-01-12T16:47:29+0000 lvl=eror msg="run errored out. retrying" id=1742189 context="RunContext{ID:1742189 GUID:c6eaac68cd12f543bfa3e0c3905d68cc ProblemName:String-Binario-Secreto, Run{AttemptID:2637165062400792792 Language:cpp InputHash:1ca340a262bfeef863d2bdc602d85bd06c418631}}" stack=[main.registerHandlers.func4(omegaup-grader/handler.go:399)]```

Log del runner:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x73eaba]

goroutine 1 [running]:
github.com/omegaup/quark/runner.Grade(0xc00009f180, 0x9e3020, 0xc000f29c20, 0xc000bb0550, 0x9ec7a0, 0xc000454840, 0x9e7a80, 0xd6a3e8, 0x0, 0x0, ...)
    /home/vagrant/quark/src/github.com/omegaup/quark/runner/runner.go:658 +0x888a
main.gradeRun(0xc00009f180, 0xc000125560, 0xc000bb0550, 0xc000bbe630, 0x0, 0x0, 0x0)
    /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:547 +0x542
main.gradeAndUploadResults(0xc00009f180, 0xc000125560, 0xc000558180, 0x3a, 0xc000bb0550, 0xc000beb260, 0x0, 0x0)
    /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:419 +0x1c3
main.processRun(0xc00009f680, 0xc000125560, 0xc00011c500, 0x0, 0x0)
    /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:375 +0x3a2
main.main()
    /home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:245 +0x1494```

**Comment by lhchavez** [comment]
al parecer se cacheó una versión incorrecta del problema en los runners. estoy purgando esa versión de ese problema y un par de otros problemas donde está ocurriendo lo mismo.

**Comment by lhchavez** [comment]
mentira! el problema está malconfigurado! dice que usa un validador custom pero no provee uno.

el fix es dejar de confiar en el problema >_>.

**Comment by frcepeda** [comment]
wat

en mis logs tengo que sí se subió un validador https://circleci.com/gh/ComiteMexicanoDeInformatica/PES-2019/153

```2018-12-14 16:21:22,183: writing diciembre/stringbinariosecreto/validator.py
[...]
2018-12-14 16:21:24,495: Response: {'uploaded_files': ['validator.py', 'interactive/stringSecreto.idl',[...]
```

El mensaje de ese commit debería ser `Deployed automatically from commit c01eed0c7607732f194e68c0c655a768b9c248c5`

**Comment by frcepeda** [comment]
(además según yo omegaUp rechaza el update si dices que tienes validador custom pero no hay, no?)

**Comment by lhchavez** [comment]
oh! ya vi qué pasó. el script de migración decidió ignorar el validador porque en _un_ commit no se lo diste. la intención era solo ignorar el validador en ese commit, pero al parecer se guardó ese hack para commits futuros.

**Comment by frcepeda** [comment]
Va, tú le mueves o yo hago upload otra vez? Me da cosita hacer rejudge porque creo que aún no contamos los puntajes de esos exámenes

**Comment by lhchavez** [comment]
le hago amend yo. queda resuelto como en media hora.
