### ISSUE TITLE
OmegaUp no evalúa envíos y se quedan en 'new'

### ISSUE THREAD

**Issue by darknut** [omegaup/omegaup#2355]
Al enviar un código, específicamente envíos

7b100e82
7baadc9b
bc4c8565
ec425649
c1f6ae44
b8f685d9

para el problema Planetas, no se evalúan y se quedan en 'new'

Envié tres códigos diferentes (dos de ellos códigos que ya daban 100), y todos siguen en 'new'

![image](https://user-images.githubusercontent.com/123875/52026868-3d291700-24be-11e9-9268-a3aae93aaad8.png)

(El código de en medio sin puntos es un hola mundo)

**Comment by darknut** [comment]
Se parece el issue #2316

**Comment by lhchavez** [comment]
Log del runner:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x749726]

goroutine 1 [running]:
github.com/omegaup/quark/runner.CalculateScore(0xc000171758, 0x9e42c0, 0xc00000ed78, 0x9e42c0, 0xc00000ed70, 0xc00038a980, 0x9, 0x0, 0xc000630640)
	/home/vagrant/quark/src/github.com/omegaup/quark/runner/validator.go:72 +0x5a6
github.com/omegaup/quark/runner.Grade(0xc00021ea00, 0x9e3e80, 0xc0003e5820, 0xc000347360, 0x9ed600, 0xc0003440c0, 0x9e88e0, 0xd6b408, 0x0, 0x0, ...)
	/home/vagrant/quark/src/github.com/omegaup/quark/runner/runner.go:1118 +0x5ac1
main.gradeRun(0xc00021ea00, 0xc00022e300, 0xc000347360, 0xc000c477d0, 0x0, 0x0, 0x0)
	/home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:556 +0x542
main.gradeAndUploadResults(0xc00021ea00, 0xc00022e300, 0xc000129140, 0x3a, 0xc000347360, 0xc0009ae780, 0x0, 0x0)
	/home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:428 +0x1c3
main.processRun(0xc00009f680, 0xc00022e300, 0xc00011c600, 0x0, 0x0)
	/home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:384 +0x3a2
main.main()
	/home/vagrant/quark/src/github.com/omegaup/quark/cmd/omegaup-runner/main.go:254 +0x1532
```

se parece, pero es ligeramente distinto. en este caso parece que no está encontrando la tolerancia: https://github.com/omegaup/quark/blob/f0a71330d0116f64127c7fc049d1fef77de1f41f/runner/validator.go#L72
