### ISSUE TITLE
test_user_ranking_course está flaky después de introducir #2614

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2699]
Después de haberle dado merge a #2614, hay algo de flakiness en la prueba `test_user_ranking_course`.

```

=================================== FAILURES ===================================
_______________________ test_user_ranking_course[chrome] _______________________
[gw1] linux -- Python 3.5.2 /usr/bin/python3.5
>       lambda: ihook(item=item, **kwds),
        when=when,
    )
../../../.local/lib/python3.5/site-packages/flaky/flaky_pytest_plugin.py:306: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
frontend/tests/ui/util.py:94: in _wrapper
    return f(driver, *args, **kwargs)
/usr/lib/python3.5/contextlib.py:77: in __exit__
    self.gen.throw(type, value, traceback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
driver = <ui.conftest.Driver object at 0x7f7bd0c39550>
    @contextlib.contextmanager
    def assert_no_js_errors(driver, *, path_whitelist=(), message_whitelist=()):
        '''Shows in a list unexpected errors in javascript console'''
        driver.log_collector.push()
        try:
            yield
        finally:
            unexpected_errors = []
            for entry in driver.log_collector.pop():
                if 'WebSocket' in entry['message']:
                    # Travis does not have broadcaster yet.
                    continue
                if is_path_whitelisted(entry['message'], path_whitelist):
                    continue
                if is_message_whitelisted(entry['message'], message_whitelist):
                    continue
                unexpected_errors.append(entry['message'])
>           assert not unexpected_errors, '\n'.join(unexpected_errors)
E           AssertionError: http://localhost:8000/third_party/js/sugar.js?ver=418ff9 55:242 
Uncaught TypeError: Invalid locale.
E           http://localhost:8000/js/dist/commons.js?ver=897396 982:66 Uncaught TypeError: 
Cannot read property 'shouldShowFirstAssociatedIdentityRunWarning' of null
frontend/tests/ui/util.py:142: AssertionError
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in 
_wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_course.py", line 
40, in test_user_ranking_course
                                  problem)))).click()
                                File 
"/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, 
in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in 
_wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_course.py", 
line 40, in test_user_ranking_course
                                  problem)))).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
===Flaky Test Report===
test_user_ranking_course[chrome] failed (1 runs remaining out of 2).
	<class 'AssertionError'>
	http://localhost:8000/third_party/js/sugar.js?ver=418ff9 55:242 Uncaught TypeError: 
Invalid locale.
http://localhost:8000/js/dist/commons.js?ver=897396 982:66 Uncaught TypeError: 
Cannot read property 'shouldShowFirstAssociatedIdentityRunWarning' of null
	[<TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/flaky/flaky_pytest_plugin.py:306>, 
<TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:94>, 
<TracebackEntry /usr/lib/python3.5/contextlib.py:77>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:142>]
test_user_ranking_course[chrome] failed; it passed 0 out of the required 1 times.
	<class 'AssertionError'>
	http://localhost:8000/third_party/js/sugar.js?ver=418ff9 55:242 Uncaught TypeError: 
Invalid locale.
http://localhost:8000/js/dist/commons.js?ver=897396 982:66 Uncaught TypeError: 
Cannot read property 'shouldShowFirstAssociatedIdentityRunWarning' of null
	[<TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/flaky/flaky_pytest_plugin.py:306>, 
<TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:94>, 
<TracebackEntry /usr/lib/python3.5/contextlib.py:77>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:142>]
test_user_ranking_contest_when_scoreboard_show_time_finished[chrome] passed 1 out of the 
required 1 times. Success!
test_create_contest[chrome] passed 1 out of the required 1 times. Success!
test_create_user[chrome] passed 1 out of the required 1 times. Success!
test_user_ranking_contest[chrome] failed (1 runs remaining out of 2).
	<class 'selenium.common.exceptions.WebDriverException'>
	Message: unknown error: Element <button type="submit" class="btn btn-primary 
user-add-single">...</button> is not clickable at point (567, 322). Other element would 
receive the click: <strong class="tt-highlight">...</strong>
  (Session info: chrome=69.0.3497.81)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
	[<TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:91>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:114>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:274>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:114>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:376>, <TracebackEntry 
/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:49>, <TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py:80>, 
<TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py:633>, 
<TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py:321>, 
<TracebackEntry 
/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py:242>]

test_user_ranking_contest[chrome] passed 1 out of the required 1 times. Success!
test_login[chrome] passed 1 out of the required 1 times. Success!
===End Flaky Test Report===
=============== 1 failed, 5 passed, 1 skipped in 599.82 seconds ================
The command "stuff/travis/run.sh "${TEST_SUITE}" script" exited with 1.
```

**Comment by pabo99** [comment]
Ya quedó solucionado en el PR #2703 con estás [líneas](https://github.com/omegaup/omegaup/pull/2703/files#diff-9660d6c851f3736793f8dd538d28f8e3R66-R73)
