### ISSUE TITLE
test_user_ranking_contest_when_scoreboard_show_time_finished está bastante flaky últimamente

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#2722]
no se qué cambio lo ocasionó, pero lleva un par de días que está flaky y hay que correr Travis varias veces.

```
_____ test_user_ranking_contest_when_scoreboard_show_time_finished[chrome] _____
[gw0] linux -- Python 3.5.2 /usr/bin/python3.5
driver = <ui.conftest.Driver object at 0x7f159693b390>
    @util.no_javascript_errors()
    @util.annotate
    def test_user_ranking_contest_when_scoreboard_show_time_finished(driver):
        '''Tests creating a contest and reviewing ranking contest when
        scoreboard show time has finished.
        '''
    
        run_id = driver.generate_id()
        alias = 'utrank_contest_%s' % run_id
        problem = 'sumas'
        user1 = 'ut_rank_user_1_%s' % run_id
        user2 = 'ut_rank_user_2_%s' % run_id
        password = 'P@55w0rd'
    
        driver.register_user(user1, password)
        driver.register_user(user2, password)
    
        create_contest_admin(driver, alias, problem, [user1, user2],
>                            driver.user_username, scoreboard_time_percent=0)
frontend/tests/ui/test_contest.py:192: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
frontend/tests/ui/util.py:114: in _wrapper
    return f(driver, *args, **kwargs)
frontend/tests/ui/test_contest.py:274: in create_contest_admin
    add_students_bulk(driver, users)
frontend/tests/ui/util.py:114: in _wrapper
    return f(driver, *args, **kwargs)
frontend/tests/ui/test_contest.py:405: in add_students_bulk
    % user)))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <selenium.webdriver.support.wait.WebDriverWait (session="ba24dad2e67a44c9a442129695b404aa")>
method = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f15968dceb8>
message = ''
    def until(self, method, message=''):
        """Calls the method provided with the driver as an argument until the \
        return value is not False."""
        screen = None
        stacktrace = None
    
        end_time = time.time() + self._timeout
        while True:
            try:
                value = method(self._driver)
                if value:
                    return value
            except self._ignored_exceptions as exc:
                screen = getattr(exc, 'screen', None)
                stacktrace = getattr(exc, 'stacktrace', None)
            time.sleep(self._poll)
            if time.time() > end_time:
                break
>       raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:
../../../.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 284, in create_contest_admin
                                  '//a[starts-with(@href, "%s")]' % contest_url))).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 192, in test_user_ranking_contest_when_scoreboard_show_time_finished
                                  driver.user_username, scoreboard_time_percent=0)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 284, in create_contest_admin
                                  '//a[starts-with(@href, "%s")]' % contest_url))).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 405, in add_students_bulk
                                  % user)))
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 274, in create_contest_admin
                                  add_students_bulk(driver, users)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 405, in add_students_bulk
                                  % user)))
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
ERROR    root:conftest.py:269 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 192, in test_user_ranking_contest_when_scoreboard_show_time_finished
                                  driver.user_username, scoreboard_time_percent=0)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 274, in create_contest_admin
                                  add_students_bulk(driver, users)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 114, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 405, in add_students_bulk
                                  % user)))
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 80, in until
                                  raise TimeoutException(message, screen, stacktrace)
                              selenium.common.exceptions.TimeoutException: Message:
===Flaky Test Report===
test_user_ranking_course[chrome] passed 1 out of the required 1 times. Success!
test_user_ranking_contest_when_scoreboard_show_time_finished[chrome] failed (1 runs remaining out of 2).
	<class 'selenium.common.exceptions.TimeoutException'>
	Message: 
	[<TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:192>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:114>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:284>, <TracebackEntry /home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py:80>]
test_user_ranking_contest_when_scoreboard_show_time_finished[chrome] failed; it passed 0 out of the required 1 times.
	<class 'selenium.common.exceptions.TimeoutException'>
	Message: 
	[<TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:192>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:114>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:274>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py:114>, <TracebackEntry /home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py:405>, <TracebackEntry /home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py:80>]
test_create_contest[chrome] passed 1 out of the required 1 times. Success!
test_create_user[chrome] passed 1 out of the required 1 times. Success!
test_user_ranking_contest[chrome] passed 1 out of the required 1 times. Success!
test_login[chrome] passed 1 out of the required 1 times. Success!
===End Flaky Test Report===
=============== 1 failed, 5 passed, 1 skipped in 375.34 seconds ================
The command "stuff/travis/run.sh "${TEST_SUITE}" script" exited with 1.
```

**Comment by pabo99** [comment]
El día de ayer ya estuvo más estable `Travis`, parece que le está ayudando el reforzar los `xpaths` que estamos actualizando. 

Continuamos revisando el comportamiento de estas pruebas.

**Comment by pabo99** [comment]
Hay un error que me ha estado apareciendo cuando ejecuto las pruebas:
```
frontend/tests/ui/util.py:117: in _wrapper
    return f(driver, *args, **kwargs)
frontend/tests/ui/test_contest.py:287: in create_contest_admin
    '//small/a[starts-with(@href, "%s")]' % contest_url
/usr/lib/python3.6/contextlib.py:88: in __exit__
    next(self.gen)
frontend/tests/ui/conftest.py:121: in page_transition
    self.wait.until(lambda _: self.browser.current_url != prev_url)
```

Esta falla no es tan común, además de que aparece al ejecutar otra prueba: `test_user_ranking_contest` y no en `test_user_ranking_contest_when_scoreboard_show_time_finished`. Sólo lo he visto en mi local.

**Comment by lhchavez** [comment]
tenemos otro error:

```
_____ test_user_ranking_contest_when_scoreboard_show_time_finished[chrome] _____
[gw2] linux -- Python 3.5.2 /usr/bin/python3.5
driver = <ui.conftest.Driver object at 0x7f775fdaebe0>
    @util.no_javascript_errors()
    @util.annotate
    def test_user_ranking_contest_when_scoreboard_show_time_finished(driver):
        '''Tests creating a contest and reviewing ranking contest when
        scoreboard show time has finished.
        '''
    
        run_id = driver.generate_id()
        alias = 'utrank_contest_%s' % run_id
        problem = 'sumas'
        user1 = 'ut_rank_user_1_%s' % run_id
        user2 = 'ut_rank_user_2_%s' % run_id
        password = 'P@55w0rd'
    
        driver.register_user(user1, password)
        driver.register_user(user2, password)
    
        create_contest_admin(driver, alias, problem, [user1, user2],
>                            driver.user_username, scoreboard_time_percent=0)
frontend/tests/ui/test_contest.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
frontend/tests/ui/util.py:117: in _wrapper
    return f(driver, *args, **kwargs)
frontend/tests/ui/test_contest.py:278: in create_contest_admin
    add_students_contest(driver, [user])
frontend/tests/ui/util.py:117: in _wrapper
    return f(driver, *args, **kwargs)
frontend/tests/ui/test_contest.py:381: in add_students_contest
    submit_locator=(By.CLASS_NAME, 'user-add-single'))
frontend/tests/ui/util.py:52: in add_students
    EC.element_to_be_clickable(submit_locator)).click()
../../../.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py:80: in click
    self._execute(Command.CLICK_ELEMENT)
../../../.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py:633: in _execute
    return self._parent.execute(command, params)
../../../.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f775fdae208>
response = {'sessionId': '16f7ac16c242450ba64102e1934a2308', 'status': 13, 'value': {'message': 'unknown error: Element <button t...ver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)'}}
    def check_response(self, response):
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" class="btn btn-primary user-add-single">...</button> is not clickable at point (567, 322). Other element would receive the click: <strong class="tt-highlight">...</strong>
E         (Session info: chrome=69.0.3497.81)
E         (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
../../../.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:282 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 260, in check_ranking
                                  assert ranking_problem.text in scores, ranking_problem
                              AssertionError: <selenium.webdriver.remote.webelement.WebElement (session="16f7ac16c242450ba64102e1934a2308", element="0.1432663526730089-3")>
                              assert '0.00' in ['+100.00']
                               +  where '0.00' = <selenium.webdriver.remote.webelement.WebElement (session="16f7ac16c242450ba64102e1934a2308", element="0.1432663526730089-3")>.text
ERROR    root:conftest.py:282 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 242, in test_user_ranking_contest_when_scoreboard_show_time_finished
                                  scores=['+100.00'])
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 260, in check_ranking
                                  assert ranking_problem.text in scores, ranking_problem
                              AssertionError: <selenium.webdriver.remote.webelement.WebElement (session="16f7ac16c242450ba64102e1934a2308", element="0.1432663526730089-3")>
                              assert '0.00' in ['+100.00']
                               +  where '0.00' = <selenium.webdriver.remote.webelement.WebElement (session="16f7ac16c242450ba64102e1934a2308", element="0.1432663526730089-3")>.text
------------------------------ Captured log call -------------------------------
ERROR    root:conftest.py:282 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 381, in add_students_contest
                                  submit_locator=(By.CLASS_NAME, 'user-add-single'))
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 52, in add_students
                                  EC.element_to_be_clickable(submit_locator)).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
                                  self._execute(Command.CLICK_ELEMENT)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
                                  return self._parent.execute(command, params)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
                                  self.error_handler.check_response(response)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
                                  raise exception_class(message, screen, stacktrace)
                              selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" class="btn btn-primary user-add-single">...</button> is not clickable at point (567, 322). Other element would receive the click: <strong class="tt-highlight">...</strong>
                                (Session info: chrome=69.0.3497.81)
                                (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
ERROR    root:conftest.py:282 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 278, in create_contest_admin
                                  add_students_contest(driver, [user])
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 381, in add_students_contest
                                  submit_locator=(By.CLASS_NAME, 'user-add-single'))
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 52, in add_students
                                  EC.element_to_be_clickable(submit_locator)).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
                                  self._execute(Command.CLICK_ELEMENT)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
                                  return self._parent.execute(command, params)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
                                  self.error_handler.check_response(response)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
                                  raise exception_class(message, screen, stacktrace)
                              selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" class="btn btn-primary user-add-single">...</button> is not clickable at point (567, 322). Other element would receive the click: <strong class="tt-highlight">...</strong>
                                (Session info: chrome=69.0.3497.81)
                                (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
ERROR    root:conftest.py:282 Traceback (most recent call last):
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 194, in test_user_ranking_contest_when_scoreboard_show_time_finished
                                  driver.user_username, scoreboard_time_percent=0)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 278, in create_contest_admin
                                  add_students_contest(driver, [user])
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 117, in _wrapper
                                  return f(driver, *args, **kwargs)
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/test_contest.py", line 381, in add_students_contest
                                  submit_locator=(By.CLASS_NAME, 'user-add-single'))
                                File "/home/travis/build/omegaup/omegaup/frontend/tests/ui/util.py", line 52, in add_students
                                  EC.element_to_be_clickable(submit_locator)).click()
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
                                  self._execute(Command.CLICK_ELEMENT)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
                                  return self._parent.execute(command, params)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
                                  self.error_handler.check_response(response)
                                File "/home/travis/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
                                  raise exception_class(message, screen, stacktrace)
                              selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button type="submit" class="btn btn-primary user-add-single">...</button> is not clickable at point (567, 322). Other element would receive the click: <strong class="tt-highlight">...</strong>
                                (Session info: chrome=69.0.3497.81)
                                (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.10586 x86_64)
```
