### ISSUE TITLE
[BUG] Calling endpoint: /api/problem/update regresa error

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#4527]
## Comportamiento Esperado

Que al hacer la llamada, se actualice el problema.

## Comportamiento Actual
La respuesta es 
```
Response: {'status': 'error', '_id': '5f3b3e18c4b61045478184', 'error': 'Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.', 'errorcode': 400, 'header': 'HTTP/1.1 400 Bad Request', 'errorname': 'Failed to query MySQL (2006): MySQL server has gone away'}
Traceback (most recent call last):
  File "upload.py", line 91, in <module>
    oUp.uploadProblem(pConfig, canCreate, zipPath, message)
  File "/home/runner/work/pes-2020/pes-2020/utils/omegaUp.py", line 157, in uploadProblem
    self.query("POST", endpoint, payload, files)
  File "/home/runner/work/pes-2020/pes-2020/utils/omegaUp.py", line 40, in query
    raise Exception(response)
Exception: {'status': 'error', 'header': 'HTTP/1.1 400 Bad Request', 'error': 'Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.', 'errorcode': 400, '_id': '5f3b3e18c4b61045478184', 'errorname': 'Failed to query MySQL (2006): MySQL server has gone away'}
```

## Pasos para reproducir (para bugs)
```
2020-08-18 02:33:58,477: Calling endpoint: /api/problem/update
2020-08-18 02:33:58,477: Payload: {'languages': 'c11-gcc,c11-clang,cpp11-gcc,cpp11-clang,cpp17-gcc,cpp17-clang,cs,hs,java,lua,pas,py2,py3,rb', 'problem_alias': 'consola-marciana', 'title': 'Videojuego Marciano', 'visibility': 'private', 'memory_limit': 131072, 'input_limit': 134217728, 'overall_wall_time_limit': 60000, 'extra_wall_time': 0, 'email_clarifications': 0, 'message': 'Deployed automatically from commit 811e08c7c443bb088182ada58ae0f44987e7eba8', 'output_limit': 134217728, 'time_limit': 1000, 'validator': 'token-caseless', 'source': 'PES 2020', 'validator_time_limit': 1000}
2020-08-18 02:34:30,354: Response: {'status': 'error', '_id': '5f3b3e18c4b61045478184', 'error': 'Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.', 'errorcode': 400, 'header': 'HTTP/1.1 400 Bad Request', 'errorname': 'Failed to query MySQL (2006): MySQL server has gone away'}
Traceback (most recent call last):
  File "upload.py", line 91, in <module>
    oUp.uploadProblem(pConfig, canCreate, zipPath, message)
  File "/home/runner/work/pes-2020/pes-2020/utils/omegaUp.py", line 157, in uploadProblem
    self.query("POST", endpoint, payload, files)
  File "/home/runner/work/pes-2020/pes-2020/utils/omegaUp.py", line 40, in query
    raise Exception(response)
Exception: {'status': 'error', 'header': 'HTTP/1.1 400 Bad Request', 'error': 'Oops. Ocurrió un error interno. Por favor inténtalo nuevamente.', 'errorcode': 400, '_id': '5f3b3e18c4b61045478184', 'errorname': 'Failed to query MySQL (2006): MySQL server has gone away'}
```

## Contexto
No podemos completar el flujo de CI del repo del COMI para el PES.

## Tu ambiente

Github actions https://github.com/frcepeda/omegaUp-deploy/blob/af583c8e9d9faefefa1498d7d5bd5ae7a1a61bae/omegaUp.py#L105

**Comment by lhchavez** [comment]
Después de unos cambios que se hicieron hace unas semanas, ya no hemos vuelto a ver "MySQL server has gone away" en los logs.
