### ISSUE TITLE
[BUG] El ranking general no se está actualizando

### ISSUE THREAD

**Issue by heduenas** [omegaup/omegaup#4943]
Hasta donde alcanzo a ver es porque un user_id tiene dos identidades asociadas a el.
Logs del cronjob en produccion:
```
2020-11-23 23:19:01,780:update_ranks.py:Started
2020-11-23 23:19:01,813:update_ranks.py:Updating accepted stats for problems...
2020-11-23 23:19:23,263:update_ranks.py:Updating users stats...
2020-11-23 23:19:23,444:update_ranks.py:Updating user rank...
2020-11-23 23:19:49,356:update_ranks.py:Failed to update user ranking
Traceback (most recent call last):
  File "/opt/omegaup/stuff/cron/update_ranks.py", line 703, in update_users_stats
    scores = update_user_rank(cur)
  File "/opt/omegaup/stuff/cron/update_ranks.py", line 165, in update_user_rank
    cur.execute('''
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'xxxxx' for key 'User_Rank.PRIMARY'")
2020-11-23 23:19:49,356:update_ranks.py:Failed to update all users stats
Traceback (most recent call last):
  File "/opt/omegaup/stuff/cron/update_ranks.py", line 703, in update_users_stats
    scores = update_user_rank(cur)
  File "/opt/omegaup/stuff/cron/update_ranks.py", line 165, in update_user_rank
    cur.execute('''
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'xxxxx' for key 'User_Rank.PRIMARY'")
2020-11-23 23:19:49,358:update_ranks.py:Updating schools stats...
2020-11-23 23:19:49,358:update_ranks.py:Updating schools solved problems...
2020-11-23 23:20:55,109:update_ranks.py:Updating school rank...
2020-11-23 23:21:04,389:update_ranks.py:Updating the candidates to school of the month...
2020-11-23 23:21:10,661:update_ranks.py:Schools stats updated
2020-11-23 23:21:10,661:update_ranks.py:Done
```

**Comment by pabo99** [comment]
Es correcto, antes no existía el problema porque la relación usuario - identidad era 1 : 1. Ahora que ya existen usuarios con más de una identidad se debe replantear el query del cronjob que genera los resultados de la tabla `User_Rank`
