### ISSUE TITLE
Requerir el correo de manera explicita cuando solicitamos los permisos de Facebook. 

### ISSUE THREAD

**Issue by alanboy** [omegaup/omegaup#698]
Cuando FB no nos da correo, createuser falla.

```
2015-07-23T08:13:26+00:00 [INFO]: /login/?redirect=%2F&code=<<<edited>>> User is logged in via facebook !! (/opt/omegaup/frontend/server/controllers/SessionController.php:395)
2015-07-23T08:13:26+00:00 [ERROR]: /login/?redirect=%2F&code=<<<edited>>> Unable to login via Facebook exception 'InvalidParameterException' with message 'parameterEmpty' in /opt/omegaup/frontend/server/libs/Validators.php:255
Stack trace:
#0 /opt/omegaup/frontend/server/libs/Validators.php(20): Validators::throwIfNotPresent(NULL, 'email', true)
#1 /opt/omegaup/frontend/server/controllers/UserController.php(28): Validators::isEmail(NULL, 'email')
#2 /opt/omegaup/frontend/server/controllers/SessionController.php(425): UserController::apiCreate(Object(Request))
#3 /opt/omegaup/frontend/www/login.php(28): SessionController->LoginViaFacebook()
#4 {main} (/opt/omegaup/frontend/server/controllers/SessionController.php:427)
```

**Comment by pabloaguilar** [comment]
Estoy ya esta listo, no? Lo pedimos de manera explicita (como permiso solicitado en la API) y falla la creacion de la cuenta si no nos lo dan.
Falta algo mas?

**Comment by lhchavez** [comment]
Ese log ya no se ha aparecido en semanas. Cerrando.
