### ISSUE TITLE
[BUG] El editor ephemeral no se muestra en problemas interactivos

### ISSUE THREAD

**Issue by pabloaguilar** [omegaup/omegaup#7827]
## Comportamiento Actual

Los problemas interactivos no tienen editor en la vista de problema. Y si tienen en concursos, pero no muestran la plantilla correcta.

## Comportamiento Esperado

Los problemas interactivos deberían mostrar el editor y el editor debería mostrar la plantilla correcta y no la plantilla default del lenguaje seleccionado.

## Si es necesario agrega la siguiente información (de lo contrario borra la sección):
*Provee una liga a un ejemplo, o una lista de pasos detallada de cómo reproducir este bug.* 
  
	1. Entrar a la vista *de problema* de un problema interactivo. Por ejemplo: https://omegaup.com/arena/problem/ofmi-2023-arreglando-huerto/ https://omegaup.com/arena/problem/Torneo-De-Uno/ o https://omegaup.com/arena/problem/FindShip/
	2.  El editor no se muestra y se muestra un error en la consola como el que copié abajo

Nota que el editor sí se al ver el problema dentro de un concurso, ese mismo problema tiene editor dentro de un concurso pero otra vez no muestra la plantilla (es decir, https://github.com/omegaup/omegaup/issues/7670 debería abrirse otra vez)

*Detalles relevantes acerca del ambiente en el que reprodujiste este bug*

	* Nombre del navegador (e.g. Chrome 39, node.js 5.4): Chrome  y Firefox, sucede en ambos
	* De la consola de desarrollador de Chrome:
```
details.ts:63 TypeError: Cannot read properties of undefined (reading 'extension')
    at h.Interactive (RunDetailsPopup.vue:418:53)
    at vuex.esm.js:740:13
    at vuex.esm.js:392:7
    at Array.forEach (<anonymous>)
    at vuex.esm.js:391:11
    at h._withCommit (vuex.esm.js:522:3)
    at h.commit (vuex.esm.js:390:8)
    at commit (vuex.esm.js:335:19)
    at h.initProblem (RunDetailsPopup.vue:279:7)
    at Array.<anonymous> (vuex.esm.js:747:23)
Runs.vue:492 TypeError: Cannot read properties of undefined (reading 'modelMapping')
    at a.mounted (Runs.vue:517:43)
    at ze (vue.common.prod.js:6:11225)
    at Qt (vue.common.prod.js:6:25167)
    at Object.insert (vue.common.prod.js:6:20196)
    at k (vue.common.prod.js:6:60009)
    at Pi.nodeOps [as __patch__] (vue.common.prod.js:6:61367)
    at e._update (vue.common.prod.js:6:34364)
    at wn.r (vue.common.prod.js:6:67988)
    at pn.get (vue.common.prod.js:6:26596)
    at new pn (vue.common.prod.js:6:26514)
details.ts:63 TypeError: Cannot read properties of undefined (reading 'extension')
    at get filename (Runs.vue:496:32)
    at pn.get (vue.common.prod.js:6:26596)
    at pn.evaluate (vue.common.prod.js:6:27746)
    at a.filename (vue.common.prod.js:6:29650)
    at get title (Runs.vue:497:39)
    at pn.get (vue.common.prod.js:6:26596)
    at pn.evaluate (vue.common.prod.js:6:27746)
    at a.title (vue.common.prod.js:6:29650)
    at Object.<anonymous> (Runs.vue:496:5)
    at r.container.ItemContainer.emit (goldenlayout.js:255:30)
```

**Comment by HNOONa-0** [comment]
On it!

**Comment by pabloaguilar** [comment]
Thanks for the quick reply @HNOONa-0 

I think this partially fixed the issue in that the editor now shows up, which is definitely better than what we had before where the editor failed to load. That said, the issue is still not fully fixed.

None of the interactive problems are showing the proper template yet.

C++ templates show "Not supported" and all other languages show an incorrect template.

This is what I see for C++:
![image](https://github.com/user-attachments/assets/11a5e4b8-d501-4e43-b989-b61c011ee5a5)

and what I see for Python:
![image](https://github.com/user-attachments/assets/c88e6487-168e-4286-8cd2-0d9328a6f298)

**Comment by HNOONa-0** [comment]
@pabloaguilar Sorry about that, I believe this PR will surely fix that issue.
